---
- name: Create users on the Linux!
  hosts: all
  tasks:
  - name: Creating user and Expire password!
    user:
       name: "{{ item.name }}"
       password: "{{ password | password_hash('sha512') }}"
       state: present
    with_subelements:
         - "{{ users }}"

  - name: Expire password!
    command: chage -d 0 {{ item.name }}
    with_subelements:
         - "{{ users }}"

  - name: Create group!
    command: groupadd "{{ item.group }}"
    with_subelements:
         - "{{ users }}"

  - name: Append user to group
    user:
       name: "{{ item.name }}"
       shell: /bin/bash
       groups: "{{ item.group }}"
       append: yes
    with_subelements:
         - "{{ users }}"
...
