---
- name: Create users on the Linux!
  hosts: all
  tasks:
  - name: Creating user and Expire password!
    user:
       name: "{{ item }}"
       password: "{{ password | password_hash('sha512') }}"
       state: present
       expires: 0
    with_items:
         - "{{ vm }}"
         - "{{ dev }}"

  #- name: Expire password!
  #  chage:
  #      user: "{{ item }}"
  #      sp_lstchg: 0
  #  with_items:
  #       - "{{ vm }}"
  #       - "{{ dev }}"

  - name: Create group!
    command: groupadd "{{ item }}"
    with_items:
         - "{{ vm.kbzgateway }}"
         - "{{ dev.kbzgateway }}"

  - name: Append user to group
    user:
       name: "{{ item }}"
       shell: /bin/bash
       groups: it.kbzgateway
       append: yes
    with_items:
         - "{{ vm.kbzgateway }}"
         - "{{ dev.kbzgateway }}"
...
