---
- name: Create users on the Linux!
  hosts: all
  tasks:
  - name: Creating user and Expire password!
    user:
       name: "{{ item }}"
       password: "{{ password | password_hash('sha512') }}"
       state: present
    loop:
         - "{{ user1 }}"
         - "{{ user2 }}"

  - name: Expire password!
    command: chage -d 0 {{ item }}
    with_subelements:
         - "{{ user1 }}"
         - "{{ user2 }}"

  - name: Create group!
    command: groupadd "{{ item }}"
    loop:
         - "{{ group1 }}"
         - "{{ group2 }}"
         

  - name: Append user to group
    user:
       name: "{{ item.name }}"
       shell: /bin/bash
       groups: "{{ item.groups }}"
       append: yes
    loop:
         - "[ name: {{ user1 }} , groups: {{ group1 }} ]"
         - "[ name: {{ user2 }} , groups: {{ group2 }} ]"
...
