---
- name: Create users on the Linux!
  hosts: all
  tasks:
  - name: Creating user1!
    user:
       name: "{{ item }}"
       password: "{{ password | password_hash('sha512') }}"
       state: present
    with_items:
         - "{{ user1 }}"
         
  - name: Creating user2!
    user:
       name: "{{ item }}"
       password: "{{ password | password_hash('sha512') }}"
       state: present
    with_items:
         - "{{ user2 }}"

  - name: Expire password1!
    command: chage -d 0 {{ item }}
    with_items:
         - "{{ user1 }}"
   
  - name: Expire password1!
    command: chage -d 0 {{ item }}
    with_items:
         - "{{ user2 }}"

  - name: Create group1!
    command: groupadd "{{ item }}"
    with_items:
         - "{{ group1 }}"
         
  - name: Create group2!
    command: groupadd "{{ item }}"
    with_items:
         - "{{ group2 }}"
         

  - name: Append user to group1
    user:
       name: "{{ item }}"
       shell: /bin/bash
       groups: "{{ group1 }}"
       append: yes
    loop:
         - "{{ user1 }}"
   
  - name: Append user to group2
    user:
       name: "{{ item }}"
       shell: /bin/bash
       groups: "{{ group2 }}"
       append: yes
    loop:
         - "{{ user2 }}"
...
